function disp_pelatihan(object_handle,event)
  %Menambah figure baru
  pelatihan_f = figure("2","name","Mulai Pelatihan Motor","toolbar","none",...
                                "menubar","none");
  %Holder Path Img Baru
  pathImgLatih = uicontrol ("style","text",'units','normalized',"string",...
                "Buka Image Latih",'units','normalized',...
                "position", [0.1 0.8 0.7 0.1],...
                "backgroundcolor",[1,1,1],...
                "horizontalalignment","left","fontsize",10);
                
  namafile_h = uicontrol ("visible","off","style","text",'units','normalized',"string",...
                "",'units','normalized',...
                "position", [0.1 0.8 0.7 0.1],...
                "backgroundcolor",[1,1,1],...
                "horizontalalignment","left","fontsize",10);
                
  %agar bisa ditampilkan
  do_getimage_latih_btn = uicontrol ("style",'pushbutton',"string",...
                "Lihat Gambar",'units','normalized',...
                "visible","off","fontsize",8,...
                "position", [0.8 0.825 0.15 0.05],"callback",{@open_image_latih,pathImgLatih});
  %label input
  label_input_label_h = uicontrol("style",'text',"string",...
                "Masukan Label Image Latih",'units','normalized',"horizontalalignment","left",...
                "visible","off","fontsize",8,"backgroundcolor",[1,1,1],...
                "position", [0.1 0.75 0.5 0.05]);
  %input textbox
  input_label_h = uicontrol("style","edit",'units','normalized',...
                "visible","off","string","","fontsize",10,"backgroundcolor",[1,1,1],...
                "position", [0.1 0.7 0.5 0.05],"horizontalalignment","left");
                
                
  %Btn untuk load image
  do_getimage_latih_btn = uicontrol ("style",'pushbutton',"string",...
                "Buka File Image",'units','normalized',...
                "position", [0.1 0.9 0.2 0.06],"callback",{@open_getImage_latih,...
                pathImgLatih,do_getimage_latih_btn,label_input_label_h,input_label_h,...
                namafile_h});
                
  %Btn untuk latih image baru
  do_ekstrak_latih_btn = uicontrol ("style",'pushbutton',"string",...
                "Ekstrak Fitur Data Latih","fontsize",18,'units','normalized',...
                "position", [0.25 0.35 0.5 0.3],"callback",{@ekstrak_fitur_latih,...
                pathImgLatih,namafile_h,input_label_h});
  
  %Btn untuk latih jika dari csv
  do_refresh_latih_btn = uicontrol ("style",'pushbutton',"string",...
                "Refresh Data Latih","fontsize",18,'units','normalized',...
                "position", [0.25 0.05 0.5 0.3],"callback",@refresh_latih);              
endfunction